### PR TITLE
Update gradle wrapper to 6.1.1

### PR DESCRIPTION
**Pull request by jskov**
Removes plugin property information which duplicates information in
build file (and causes jar-file conflict).

### CODE REVIEW

**Comment by jskov** [comment]
@johanvos @jperedadnr 

Could someone land the #52/#53 PR please?
I would like to bring the plugin up to par with the Maven plugin.
Thanks!

**Comment by abhinayagarwal** [comment]
@jskov Can you please fork out PR #53 and create a new PR with latest changes?

**Comment by abhinayagarwal** [comment]
This PR will most probably pass when #52 is fixed

**Comment by jskovjyskebankdk** [comment]
@abhinayagarwal happy to! :)

**Comment by jskov** [comment]
@abhinayagarwal  I have submitted a new PR, so I am closing this one.

**Pull request closed without merging**
