### PR TITLE
#52 Use Substrate

### PR DESCRIPTION
**Pull request by jperedadnr**

### CODE REVIEW

**Comment by tlvenn** [comment]
@johanvos any chance to review and merge this PR please ?

**Comment by tlvenn** [comment]
Hi @jperedadnr , is this PR still WIP ? Could you update us on its status please ? Thanks in advance and merry xmas.

**Comment by johanvos** [comment]
At this moment, the client-maven-plugin is the one we support (https://github.com/gluonhq/client-maven-plugin). We can keep the gradle plugin on-par with the maven plugin, but it's a lower priority. However, if anyone wants to create PR's for the gradle plugin so that it follows the maven plugin, that would be much appreciated.

**Comment by tlvenn** [comment]
Thanks for the reply @johanvos , that's fair enough but it would probably a good idea to highlight this in the readme of the project as to set proper expectations.

**Comment by abhinayagarwal** [comment]
This PR is now outdated. If someone is willing to fork it out and create a new PR with latest changes, we would definitely review the same.

**Comment by jskovjyskebankdk** [comment]
I have a working fork, but based on the changes from this PR.
I will be happy to make a combined PR.

**Pull request closed without merging**
